### ISSUE TITLE
真机跑的时候 push 完成之后返回根控制器,再点 NEXT 去 push 会发生 crash.

### ISSUE THREAD

**Issue by coderlinxx** [JNTian/JTNavigationController#1]
真机跑的时候 push 完成之后返回根控制器,再点 NEXT 去 push(或切到另一个 tabbar 的控制器点 NEXT去push, 项目直接 crash 了,也没有任何错误提示. 估计还是设计上的问题吧.) 我用5S 跑的.

**Comment by JNTian** [comment]
是随机出现还是100%出现?

**Comment by coderlinxx** [comment]
我又测试了一下,100%  多点几下 NEXT  然后返回到根页, 就会出现 出现时,在根页继续从左边缘向右滑动,这个时候在根页上出现了 pop 的效果...

**Comment by coderlinxx** [comment]
我知道问题出在了哪里. 多点几下 NEXT 然后返回到根页 到根页之后直接点 NEXT 不会 crash, 但是如果先继续做一次或几次返回滑动手势再去点 NEXT的话,就会 crash 应该是手势冲突吧

**Comment by JNTian** [comment]
你说的这个其实并不是crash，只是卡住了。这个BUG我是知道的。并且是做了处理的啊。。为什么你那还会出现呢？是最新的代码么？我在6，6p，和5的真机都测过，并没有出现了。

**Comment by coderlinxx** [comment]
我是5s 跑的,运行后不用点 NEXT,先做一下返回的侧滑手势,再去点 NEXT, 卡住了..  100%

**Comment by coderlinxx** [comment]
是从这里 down 下来的最新代码,我自己研究了下,试着把这个 BUG 解决了,
//解决某些情况push会卡死的情况
- (void)navigationController:(UINavigationController *)navigationController didShowViewController:(UIViewController *)viewController animated:(BOOL)animated { }
这里改动了下,可以了.这份代码很棒,跟着学习了.  我是去点一下 fork 修改一下对吧

**Comment by coderlinxx** [comment]
...不知道那个东西怎么搞. 贴到这里吧.
//解决某些情况push会卡死的情况
- (void)navigationController:(UINavigationController *)navigationController didShowViewController:(UIViewController *)viewController animated:(BOOL)animated {
    
    BOOL isRootVC = viewController == navigationController.viewControllers.firstObject;
    
    if (self.fullScreenPopGestureEnable) {
        id target = self.interactivePopGestureRecognizer.delegate;
        SEL action = NSSelectorFromString(@"handleNavigationTransition:");
        
        if (isRootVC) {
            [self.popPanGesture removeTarget:target action:action];
        } else {
            [self.popPanGesture addTarget:target action:action];
        }
    }
    self.interactivePopGestureRecognizer.enabled = !isRootVC;
}
其实就是把self.interactivePopGestureRecognizer.enabled = !isRootVC;挪了下位置,不管有没有开启全屏侧滑手势,都要去判断手势是否可以使用就好了~  应该可以了.

**Comment by JNTian** [comment]
我没测试iOS7，所以iOS7貌似会有这个问题。现在改好了
