### ISSUE TITLE
如何禁止某个controller的全屏返回手势？

### ISSUE THREAD

**Issue by WenkyYuan** [JNTian/JTNavigationController#2]
项目需求，有些viewController要禁止全屏返回手势。

**Comment by WenkyYuan** [comment]
@JNTian 看看我的fork里面的解决办法可以么？
在需要禁止全屏返回手势的界面viewWillApeare里调用[JTBaseNavigationController shareNavgationController].fullScreenPopGestureEnable = NO;
在viewWillDisappear调用[JTBaseNavigationController shareNavgationController].fullScreenPopGestureEnable = YES;

**Comment by JNTian** [comment]
等年后不那么忙再优化一下代码和需求。

**Comment by JNTian** [comment]
已近更新的.你尝试用下新的版本.集成方法也有所不同
