### ISSUE TITLE
Jt_navigationController 应改为weak的，否则会造成循环引用，无法释放

### ISSUE THREAD

**Issue by 276523923** [JNTian/JTNavigationController#29]
这个要改成 OBJC_ASSOCIATION_ASSIGN
- (void)setJt_navigationController:(JTNavigationController *)navigationController {
    objc_setAssociatedObject(self, @selector(jt_navigationController), navigationController, OBJC_ASSOCIATION_ASSIGN);
}

**Comment by JNTian** [comment]
已修复
