### ISSUE TITLE
代码探讨

### ISSUE THREAD

**Issue by Winter-Yang** [JNTian/JTNavigationController#5]
由于最近我也在封装一些框架类的东西，所以中间部分参考了你的部分代码，目前已知的可优化部分，在于设置window.rootViewController，这部分需要首先设置MainViewController的navigationController为window的rootViewController，push才起作用，而在很大情况下，很多开发者习惯于将TabViewController设置为window的rootViewController，TabViewController在嵌套NavigationController，当然此处你的代码这样写的目的我还没有看出来，不知道是什么原因，希望探讨一下

**Comment by JNTian** [comment]
你可以看看我博文中详细的分析过程, rootViewController这个JTBaseNavigationController其实才是真正做push和pop操作的导航控制器,而其他的JTNavigationController只是为了使用其NavigationBar而已.

**Comment by Winter-Yang** [comment]
为什么不用自控制器来控制视图的push和pop那

**Comment by JNTian** [comment]
我最初的实现是直接用JTNavigationController来push和pop的,但是发现在有UITabBarController时,push的控制器如果存在scrollview,底部会出现tabbar高度一样的contentInset(以后有时间会加入push不隐藏tabbar的功能,那个功能的实现就是直接用JTNavigationController来管理push和pop等操作),网易云音乐其实也是这样做的, rootViewController为JTBaseNavigationController,如果需要隐藏tabbar,就使用JTBaseNavigationController来push,如果不需要隐藏tabbar,就使用JTNavigationController来push.

**Comment by Winter-Yang** [comment]
哦？  我修改了你的代码，暂时还没发现这个bug，我测试一下

**Comment by Winter-Yang** [comment]
我测了下代码，push的视图含有scrollView确实会有这些问题，我解决方案如下：

1：创建BaseViewController代码如下，
2：子视图继承自BaseViewController即可 例如@interface JTViewController : BaseViewController
#注意事项  tabBarController.tabBar.translucent = YES;    必须为YES  否则push会留白
 
你可以加下这个代码测试一下，由于我这边没有其他机子，目前主要以6为测试机


@interface BaseViewController ()

@end

@implementation BaseViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.automaticallyAdjustsScrollViewInsets = NO;
    self.extendedLayoutIncludesOpaqueBars = NO;
    self.modalPresentationCapturesStatusBarAppearance = NO;
    self.navigationController.navigationBar.translucent = NO;
   // self.tabBarController.tabBar.translucent = NO;
   self.tabBarController.tabBar.translucent = YES;

    

    // Do any additional setup after loading the view.
}

**Comment by JNTian** [comment]
这样做就违背我的初衷了,就是希望原来的所有的子控制器尽量不需要做修改,更不用继承,你这样一继承,对原项目的改动就太大了,并且如果他本来就修改过这些属性的话,可能会出现未知的问题.

**Comment by Winter-Yang** [comment]
你理解错了我代码的意思，tabBarController.tabBar.translucent = YES仅仅是针对UITabBarController来处理的 ，BaseViewController里面其他配置是我工程的需求，也就是说所有的子视图是不需要进行处理的，仅仅需要处理你的mainViewController的tabBarController.tabBar.translucent = YES即可，子视图的所以配置是不需要改变的

**Comment by JNTian** [comment]
并不是所有项目都会用BaseViewController的.

**Comment by Winter-Yang** [comment]
。。。我的意思是  不需要BaseViewController，tabBarController.tabBar.translucent = YES写在你的MainViewController，bug同样解决，BaseViewController仅仅是我自己的配置

**Comment by JNTian** [comment]
你试试不继承你的BaseViewController,也就是不修改
self.automaticallyAdjustsScrollViewInsets = NO;
self.extendedLayoutIncludesOpaqueBars = NO;
self.modalPresentationCapturesStatusBarAppearance = NO;
self.navigationController.navigationBar.translucent = NO;
这些属性的时候,
tabBarController.tabBar.translucent = YES
还能解决这个BUG么

**Comment by Winter-Yang** [comment]
可以解决，上面的4个属性仅仅是配置子视图的frame用的，只要在你的根视图UITabBarController 配置tabBarController.tabBar.translucent = YES即可

/*
main
*/
@interface MainViewController ()

@end

@implementation MainViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    YQViewController *firstVC = [[YQViewController alloc] init];
    UITabBarItem *firstItem = [[UITabBarItem alloc] initWithTabBarSystemItem:UITabBarSystemItemFavorites tag:1];
    firstVC.title = @"First";
    firstVC.tabBarItem = firstItem;
    YQNavifationController *firstNav = [[YQNavifationController alloc] initWithRootViewController:firstVC];
    firstNav.tabBarItem.title = @"测试";
    self.viewControllers = @[firstNav];
   //关键
    self.tabBarController.tabBar.translucent = YES;
}

/*
son
*/
#import <UIKit/UIKit.h>

@interface YQViewController : UIViewController

@end
@implementation YQViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    NSString * str = [[NSUserDefaults standardUserDefaults] objectForKey:@"index"];
    if (str) {
        int index = [str intValue]+1;
        self.title = [NSString stringWithFormat:@"%d",index];
        [[NSUserDefaults standardUserDefaults] setObject:self.title forKey:@"index"];
    }else{
        self.title = @"0";
        [[NSUserDefaults standardUserDefaults] setObject:@"0" forKey:@"index"];

    }
    
    
    self.view.backgroundColor = [UIColor redColor];
    self.navigationController.navigationBar.barTintColor = [UIColor randomColor];
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Next" style:UIBarButtonItemStylePlain target:self action:@selector(didTapNextButton)];
    
    
    self.la = [[UIScrollView alloc]initWithFrame:CGRectMake(0, 0, 375, 668)];
    self.la.backgroundColor = [UIColor brownColor];
    self.la.contentSize = CGSizeMake(700, 10101);
    [self.view addSubview:self.la];
    // Do any additional setup after loading the view.
}

- (void)didTapNextButton {
    YQViewController *viewController = [[YQViewController alloc] init];
    [self.navigationController pushViewController:viewController animated:YES];
}

**Comment by JNTian** [comment]
tabBar.translucent默认就是YES啊

**Comment by Winter-Yang** [comment]
需要设置UITabBarController的 self.tabBarController.tabBar.translucent = YES;   而不是self.tabBar.translucent=YES.

**Comment by JNTian** [comment]
我懂你意思了,push过后self.tabBarController.tabBar.translucent会被设置为NO,改成YES问题就解决了是吧

**Comment by JNTian** [comment]
我现在改一下试试,如果可以解决的话,那集成就更简单了.

**Comment by JNTian** [comment]
并没有用...self.tabBarController.tabBar.translucent本来就是YES

**Comment by Winter-Yang** [comment]
需要修改其他源码  https://github.com/Winter-Yang/NavigationController

**Comment by JNTian** [comment]
你难道没发现你的scrollview底部永远有一定的contentInset吗?

**Comment by JNTian** [comment]
push后的页面

**Comment by Winter-Yang** [comment]
那是我创建的的scrollview的问题，我的scrollview是写死的

**Comment by JNTian** [comment]
我知道.那你试试用autolayout

**Comment by JNTian** [comment]
我找到一个办法暂时解决了那个BUG,你试试Down个最新的看看

**Comment by Winter-Yang** [comment]
OK   我一会看看
