### ISSUE TITLE
navigationBar隐藏问题

### ISSUE THREAD

**Issue by sitting2002** [JNTian/JTNavigationController#6]
//    [self.navigationController.navigationBar setHidden:YES];
    [[JTBaseNavigationController shareNavgationController].navigationBar setHidden:YES];

请教一下  某个控制器需要出现时候隐藏navigationBar   但push下一个控制器需要显示navigationBar  
再pop回来就隐藏失败了，需要做什么处理？

-(void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
//    [self.navigationController.navigationBar setHidden:YES];
    [[JTBaseNavigationController shareNavgationController].navigationBar setHidden:YES];
}

-(void)viewWillDisappear:(BOOL)animated{
    [super viewWillDisappear:animated];
//    [self.navigationController.navigationBar setHidden:NO];
}

**Comment by JNTian** [comment]
每个控制器的navigationBar都是独立的,直接在需要隐藏的控制器viewDidLoad中[self.navigationController setNavigationBarHidden:YES];就可以了.

**Comment by VaeXnn** [comment]
为什么有时候侧滑出现左半边待显示的屏幕出现黑屏现象

**Comment by JNTian** [comment]
黑屏是全黑还是部分?有截图么

**Comment by VaeXnn** [comment]
就是快要手势滑出的那部分，不是全黑

**Comment by JNTian** [comment]
试试给个背景色看看

**Comment by sitting2002** [comment]
好的 已经解决了 谢谢
